---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1r426ftmv67zur5hklj47s547zz3620xawkhzjpcvwrt952506e9q8rzh74"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1r426ftmv67zur5hklj47s547zz3620xawkhzjpcvwrt952506e9q8rzh74"
