apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:+cWlBmFrck0gGlM7MN1YIkDqJjHJyCdFLN4fS2lUtl4=,iv:Idj0W0LoHF3ynubbU9nICe4mkcDohfHfNPPfdSClnkI=,tag:tXUWbCegqGBL9dcI+edOZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r426ftmv67zur5hklj47s547zz3620xawkhzjpcvwrt952506e9q8rzh74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTWhjMG9aZjJQcmxiSFIr
            dGdQUUZkRjlGTEVqQ0MrT3ByNXJKUWU3R0ZJClZ0cXZsRU5PYlc2QTFNaWp0QlRn
            NmpvbWdtanVDSzdwcW1aUmN4elBSMlkKLS0tIG1LdkpIUy84RVZuRnRNY3NyQzZy
            QytpR1E3dlZjZUpsMkhodFV1Rmd5eFkKqTir5zh8bABCI7xCXajDOTN45tO12t+t
            WjPSX6UbVFbt5DlZY6svl6fQHA+V3z7VMCr3sF8ADlB+C7zHDYAKHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T06:48:18Z"
    mac: ENC[AES256_GCM,data:4I5ZNrY1sQDH3XDEb+xUIbG75N118IEtZGMRSvRY+yoawZAyezOk2KHNRzKkwSLdM2/+uCsNPF1eJNf5AiNkFI03Cb94S+U9/tF2A2wE0twR0XMzxAF/JNlr2/2b6PgHjIJBSY1Nh+2BbDgxXMuMag/+/IWH5uZ4rCjNmcibgDw=,iv:ZcpEDaR5ljWmxr9/ZVZKQ2nfpPiCPi3I1JMZ4yg8vdE=,tag:sqKPQP7O5K03oCdxsZXdHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
